import Head from 'next/head'
import React from 'react'

export default function categories() {
    return (
        <>
            <Head>
                <title>Categroies</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            </Head>
            <section class="cats py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <p>المرحلة الاولي</p>
                                    <p>سورة النبأ-الناس</p>
                                </div>
                                <p class="count">1</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة الثانية</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">2</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة الثالثة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">3</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة الرابعة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">4</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة الخامسة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">5</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة السادسة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">6</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة السابعة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">7</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة الثامنة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">8</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة التاسعة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">9</p>
                            </a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <a class="item">
                                <div>
                                    <i class="fa-solid fa-lock text-dark "></i>
                                    <p>المرحلة العاشرة</p>
                                    <p>سورة ...</p>
                                </div>
                                <p class="count">10</p>
                            </a>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
