import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <Link
        style={{display: "block",marginBottom: "20px"}}
        href="/login">Login</Link>
      <Link
        style={{display: "block",marginBottom: "20px"}}
        href="signup.html">Signup</Link>
      <Link
        style={{display: "block",marginBottom: "20px"}}
        href="categories.html">Categories</Link>
      <Link
        style={{display: "block",marginBottom: "20px"}}
        href="details.html">Details</Link>
    </>
  )
}
